version: '3'

services:
  node-app:
    build: .
    # environment:
    #   - PORT=9003
    image: couplewhocode11/docker-nodejs-workflow:latest
    volumes:
      - ./:/app:ro
      - /app/node_modules
    ports:
      - 9000:9000
    command: npm run start